version: "3.9"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: estufa_app
    environment:
      - MIX_ENV=prod
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
    depends_on:
      - mosquitto
    ports:
      - "4000:4000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: >
      sh -c "mix deps.get &&
             mix compile &&
             mix run --no-halt"
    networks:
      - tcc_net

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    networks:
      - tcc_net

networks:
  tcc_net:
    driver: bridge
